config/routes.rb
Rails.application.routes.draw do
resources :users
  

  root 'homes#index'

  get 'cars/index', to: 'cars#index'

  get 'cars/new', to: 'cars#new'

  get 'cars/users', to: 'cars#users'

   get 'cars/listing', to: 'cars#listing'

  get 'cars/history', to: 'cars#history'

  get 'cars/rent', to: 'cars#rent'
    post 'cars/rent', to: 'cars#rent'

  post 'cars/:id', to: 'cars#show'

  get 'cars/rented', to: 'cars#rented'
  get 'cars/accept', to: 'cars#accept'

  get 'cars/deactive', to: 'cars#deactive'
   get 'cars/reactivate', to: 'cars#reactivate'

  get 'cars/offhire', to: 'cars#offhire'

  get 'cars/rentpage', to: 'cars#rentpage'
    post 'cars/rentpage', to: 'cars#rentpage'

  get 'homes/aboutus', to: 'homes#aboutus'

   get 'histories/listing', to: 'histories#listing'

  

  get 'histories/new', to: 'histories#new'
  get 'users/show', to: 'users#show'
  
  get 'signup', to: 'users#new'
 

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

  post  'reviews/new/:id', to: 'reviews#new'
  get   'reviews/new/:id', to: 'reviews#new'
  post  'reviews/displays/:id', to: 'reviews#displays'
  get   'reviews/displays/:id', to: 'reviews#displays'

    resources :reviews
    resources :cars
    resources :histories
 resources :users, except: [:new]
end

app/models/user.rb
class User < ActiveRecord::Base
require 'carrierwave/orm/activerecord'
	
	has_many :cars

	mount_uploader :img_url, ImageUploader

has_secure_password



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create


    @user = User.new(user_params)
    @user.renter_id = 0
    @user.rentcount = 0
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id #creates an object to ID the session
      flash[:notice] = "Logged in successfully"
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:img_url, :rentcount, :username, :email, :password, :firstname, :lastname, :mobile, :dob, :firstline, :postcode, :terms)
    end
end

app/helpers/users_helper.rb
module UsersHelper


	

  def current_user
		@current_user ||= if session[:user_id]   #This checks if current user has been used before to stop inefficient database access
			User.find(session[:user_id])
		end
	end

	def logged_in?
		!!current_user  #turns it into a booleon to check if current user is true or false
	end

	def admin
		!!current_user == "Admin"
	end
end

app/views/users/_form.html.erb
<div class="backContainer">

    <%= link_to 'Back', :back, class: "backButtons" %>

        <%= form_for(@user) do |f| %>
            <% if @user.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

                    <ul>
                        <% @user.errors.full_messages.each do |message| %>
                            <li>
                                <%= message %>
                            </li>
                            <% end %>
                    </ul>
                </div>
                <% end %>

                    <div id="formContainer">
                        <div id="formTable">

                            <div class="formTableRow">
                                <div class="formTableCell">
                                    <h4><%= f.label :username %></h4>
                                </div>
                                <div class="formTableCell">
                                    <%= f.text_field :username, {:class => "formBox"} %>
                                </div>
                            </div>

                            <div class="formTableRow">
                                <div class="formTableCell">
                                    <h4><%= f.label :email %></h4>
                                </div>
                                <div class="formTableCell">
                                    <%= f.text_field :email, {:class => "formBox"} %>
                                </div>
                            </div>

                            <div class="formTableRow">
                                <div class="formTableCell">
                                    <h4><%= f.label :firstname %></h4>
                                </div>
                                <div class="formTableCell">
                                    <%= f.text_field :firstname, {:class => "formBox"} %>
                                </div>
                            </div>

                            <div class="formTableRow">
                                <div class="formTableCell">
                                    <h4><%= f.label :lastname %></h4>
                                </div>
                                <div class="formTableCell">
                                    <%= f.text_field :lastname, {:class => "formBox"} %>
                                </div>
                            </div>

                            <div class="formTableRow">
                                <div class="formTableCell">
                                    <h4><%= f.label :firstline, 'First line of home address' %></h4>
                                </div>
                                <div class="formTableCell">
                                    <%= f.text_area :firstline, {:class => "formBox"} %>
                                </div>
                            </div>

                            <div class="formTableRow">
                                <div class="formTableCell">
                                    <h4><%= f.label :postcode, 'Post code for home address' %></h4>
                                </div>
                                <div class="formTableCell">
                                    <%= f.text_field :postcode, {:class => "formBox"} %>
                                </div>
                            </div>

                            <div class="formTableRow">
                                <div class="formTableCell">
                                    <h4><%= f.label :dob, 'Date of birth' %></h4>
                                </div>
                                <div class="formTableCell">
                                    <%= f.date_select :dob, start_year: 1920, end_year: 2003, :order => [:day, :month, :year] %>
                                </div>
                            </div>

                            <div class="formTableRow">
                                <div class="formTableCell">
                                    <h4><%= f.label :mobile %></h4>
                                </div>
                                <div class="formTableCell">
                                    <%= f.text_field :mobile, {:class => "formBox"} %>
                                </div>
                            </div>

                            <div class="formTableRow">
                                <div class="formTableCell">
                                    <h4><%= f.label :password %></h4>
                                </div>
                                <div class="formTableCell">
                                    <%= f.password_field :password, {:class => "formBox"} %>
                                </div>
                            </div>
                            <div class="formTableRow">
                                <div class="formTableCell">
                                    <h4><%= f.label :img_url, "Profile picture (Optional)" %> </h4>
                                </div>
                                <div class="formTableCell">
                                    <%= f.file_field :img_url %>
                                </div>
                            </div>

                            <div class="formTableRow">
                                <div class="formTableCell">
                                    <%= f.label :contactmethod, 'Please tick here if you accept our terms and conditions on exchange of customer information', :value => 'yes' %>
                                </div>
                                <div class="formTableCell">
                                    <%= f.radio_button :terms, 'yes', :class => 'radioButton' %>
                                </div>
                            </div>
                            <div class="actions">
                                <%= f.submit :class => 'formButton' %>

                            </div>
                            <% end %>

                        </div>
                    </div>

</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', :back %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to gravatar_for(user), user_path(user) %></td>
        <td><%= link_to user.username, user_path(user)%></td>s
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Remove Listing', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="backContainer">

    <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

                <ul>
                    <% @user.errors.full_messages.each do |message| %>
                        <li>
                            <%= message %>
                        </li>
                        <% end %>
                </ul>
            </div>
            <% end %>

                <div id="formContainer">
                    <div id="formTable">

                        <div class="formTableRow">
                            <div class="formTableCell">
                                <h4><%= f.label :username %></h4>
                            </div>
                            <div class="formTableCell">
                                <%= f.text_field :username, {:class => "formBox"} %>
                            </div>
                        </div>

                        <div class="formTableRow">
                            <div class="formTableCell">
                                <h4><%= f.label :email %></h4>
                            </div>
                            <div class="formTableCell">
                                <%= f.text_field :email, {:class => "formBox"} %>
                            </div>
                        </div>

                        <div class="formTableRow">
                            <div class="formTableCell">
                                <h4><%= f.label :firstname %></h4>
                            </div>
                            <div class="formTableCell">
                                <%= f.text_field :firstname, {:class => "formBox"} %>
                            </div>
                        </div>

                        <div class="formTableRow">
                            <div class="formTableCell">
                                <h4><%= f.label :lastname %></h4>
                            </div>
                            <div class="formTableCell">
                                <%= f.text_field :lastname, {:class => "formBox"} %>
                            </div>
                        </div>

                        <div class="formTableRow">
                            <div class="formTableCell">
                                <h4><%= f.label :firstline, 'First line of home address' %></h4>
                            </div>
                            <div class="formTableCell">
                                <%= f.text_area :firstline, {:class => "formBox"} %>
                            </div>
                        </div>

                        <div class="formTableRow">
                            <div class="formTableCell">
                                <h4><%= f.label :postcode, 'Post code for home address' %></h4>
                            </div>
                            <div class="formTableCell">
                                <%= f.text_field :postcode, {:class => "formBox"} %>
                            </div>
                        </div>

                        <div class="formTableRow">
                            <div class="formTableCell">
                                <h4><%= f.label :dob, 'Date of birth' %></h4>
                            </div>
                            <div class="formTableCell">
                                <%= f.date_select :dob, start_year: 1920, end_year: 2003, :order => [:day, :month, :year] %>
                            </div>
                        </div>

                        <div class="formTableRow">
                            <div class="formTableCell">
                                <h4><%= f.label :mobile %></h4>
                            </div>
                            <div class="formTableCell">
                                <%= f.text_field :mobile, {:class => "formBox"} %>
                            </div>
                        </div>

                        <div class="formTableRow">
                            <div class="formTableCell">
                                <h4><%= f.label :password %></h4>
                            </div>
                            <div class="formTableCell">
                                <%= f.password_field :password, {:class => "formBox"} %>
                            </div>
                        </div>

                        <div class="formTableRow">
                            <div class="formTableCell">
                                <%= f.label :contactmethod, 'Please tick here if you accept our terms and conditions on exchange of customer information', :value => 'yes' %>
                            </div>
                            <div class="formTableCell">
                                <%= f.radio_button :terms, 'yes', class: "radioButton" %>
                            </div>
                        </div>
                        <div class="actions">
                            <%= f.submit :class => 'formButton' %>

                        </div>
                        <% end %>

                    </div>
                </div>

</div>

app/views/users/show.html.erb
<div id="userBG">
   <%= link_to 'Back', :back, class: "backButtons" %>
   <div id="userContainer">
      <h1> <%= @user.username %>'s Profile </h1>
      <p id="notice">
         <%= notice %>
      </p>
      <div id="userDetails">
         <%= image_tag @user.img_url.url  || 'unknown.png', :size => "120x100" %>
         <p>
            <strong>Username:</strong>
            <%= @user.username %>
         </p>
         <p>
            <strong>Name:</strong>
            <%= @user.firstname %>
            <%= @user.lastname %>
         </p>
         <% user = User.find(session[:user_id])%>
         <% if @user.id == user.id %>
         <p>
            <strong>Email:</strong>
            <%= @user.email %>
         </p>
         <p>
            <strong>Date of birth:</strong>
            <%= @user.dob %>
         </p>
         <p>
            <strong>Mobile number:</strong>
            <%= @user.mobile %>
         </p>
      </div>
      <p>
         <strong>
            <% @car = Car.all %>
      <div class="Credit">
      </div></strong></p>
      <p>
         <strong>
            Number of previous listed hires: 
            <% @Var = 0 %>
            <% @car.each do |car| %>
            <% if car.user_id == @user.id %>
            <% @Var = @Var + car.rentcount %>
            <% end %>
            <% end %>
      <div class="Credit"><%= @Var %>
      </div></strong>
      </p>
      <p>
         <strong>Number of vehicles rented by user: </strong>
      <div class="Credit">
         <%= @user.rentcount %>
      </div>
      </p>
      <h2>
         <% @Credit %>
         <strong>
            Total rating:  
            <div class="Credit"><%= @Credit = @Var +  @user.rentcount%><%= image_tag 'Review.png', :size => "10x10" %></div>
         </strong>
      </h2>
      <table id="userTable">
         <tr>
            <td>
               <%= link_to 'Edit My Account', edit_user_path(@user), class: "userButtons1" %>
            </td>
            <td>
               <%= link_to 'My Listed Cars', cars_users_path, class: "userButtons"  %>
            </td>
            <td>
               <%= link_to 'My Hire cars', cars_rented_path(), class: "userButtons"  %>
            </td>
            <td>
               <%= link_to 'Rentals History', histories_path, class: "userButtons"  %>
            </td>
            <td>
               <%= link_to 'Listing History', cars_listing_path, class: "userButtons" %>
            </td>
         </tr>
         <% else %>
         <p>
            <strong>
               Number of vehicles listed by user:<% @car = Car.all %>
               <% varr = @car.where(user_id: @user.id).count %> 
         <div class="Credit"><%= varr %>
         </div></strong></p>
         <p>
            <strong>
               Number of previous listed hires: 
               <% @Var = 0 %>
               <% @car.each do |car| %>
               <% if car.user_id == @user.id %>
               <% @Var = @Var + car.rentcount %>
               <% end %>
               <% end %>
         <div class="Credit"><%= @Var %>
         </div></strong>
         </p>
         <p>
            <strong>Number of vehicles rented by user: </strong>
         <div class="Credit">
            <%= @user.rentcount %>
         </div>
         </p>
         <h2>
            <% @Credit %>
            <strong>
               Total rating:  
               <div class="Credit"><%= @Credit = @Var + varr + @user.rentcount%><%= image_tag 'Review.png', :size => "10x10" %></div>
            </strong>
         </h2>
         <% end %>
      </table>
   </div>
</div>