config/routes.rb
Rails.application.routes.draw do
resources :users
  

  root 'homes#index'

  get 'cars/index', to: 'cars#index'

  get 'cars/new', to: 'cars#new'

  get 'cars/users', to: 'cars#users'

   get 'cars/listing', to: 'cars#listing'

  get 'cars/history', to: 'cars#history'

  get 'cars/rent', to: 'cars#rent'
    post 'cars/rent', to: 'cars#rent'

  post 'cars/:id', to: 'cars#show'

  get 'cars/rented', to: 'cars#rented'
  get 'cars/accept', to: 'cars#accept'

  get 'cars/deactive', to: 'cars#deactive'
   get 'cars/reactivate', to: 'cars#reactivate'

  get 'cars/offhire', to: 'cars#offhire'

  get 'cars/rentpage', to: 'cars#rentpage'
    post 'cars/rentpage', to: 'cars#rentpage'

  get 'homes/aboutus', to: 'homes#aboutus'

   get 'histories/listing', to: 'histories#listing'

  

  get 'histories/new', to: 'histories#new'
  get 'users/show', to: 'users#show'
  
  get 'signup', to: 'users#new'
 

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

  post  'reviews/new/:id', to: 'reviews#new'
  get   'reviews/new/:id', to: 'reviews#new'
  post  'reviews/displays/:id', to: 'reviews#displays'
  get   'reviews/displays/:id', to: 'reviews#displays'

    resources :reviews
    resources :cars
    resources :histories
 resources :users, except: [:new]
end

app/models/history.rb
class History < ActiveRecord::Base
require 'carrierwave/orm/activerecord'
	has_many :cars
	has_many :users
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy, :listing]

  # GET /histories
  # GET /histories.json
  def index
    @history = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)


  @car = Car.first
  @user = User.first
  car = @car.id
  user = @user.id
  @history.car_id = car
  @history.user_id = user


    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

   def listing
    @history = History.first
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def history_params
      params.require(:history).permit(:date)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_for @history do |f| %>

    <%= f.date_select :date, :order => [:day, :month, :year] %>

        <div class="actions">
            <%= f.submit %>
        </div>
        <% end %>

app/views/histories/edit.html.erb
	<h1>Editing History</h1>

	<%= render 'form', history: @history %>

	<%= link_to 'Show', @history %> |
	<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<div id="historiesContainer">
    <p id="notice">
        <%= notice %>
    </p>
    <%= link_to 'Back', :back, class: "backButtons" %>
        <h1>Your previous hires</h1>

        <table id="neww">
            <thead>

            </thead>

            <tbody>
                <tr>

                    <td>
                        <h4> Image </h4></td>
                    <td>
                        <h4> Make/Model</h4></td>
                    <td>
                        <h4> Date of hire</h4></td>
                    <td></td>
                </tr>
                <% @history.each do |history| %>
                    <% uid = history.user_id %>
                        <% cid = history.car_id %>
                            <% @user = User.find_by(id: uid) %>
                                <% @car = Car.find_by(id: cid)%>
                                    <% if @user == User.find(session[:user_id])%>

                                        <tr>
                                            <td>
                                                <%= image_tag @car.img_url.url || 'm4.jpg', :size => "90x80" %>
                                            </td>
                                            <td>
                                                <%= @car.manufacturer %>
                                                    <%= @car.model %> |</td>
                                            <td>
                                                <%= history.date.strftime("%I:%M  |  %F") %> |</td>
                                            <td>
                                                <%= link_to 'View car', car_path(@car) %>
                                            </td>
                                        </tr>
                                        <% end %>
                                            <% end %>
            </tbody>
        </table>

</div>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<%= @history.user_id %>
<%= @history.car_id %>
<%= @history.date %>


<%= link_to 'Back', histories_path %>