config/routes.rb
Rails.application.routes.draw do
resources :users
  

  root 'homes#index'

  get 'cars/index', to: 'cars#index'

  get 'cars/new', to: 'cars#new'

  get 'cars/users', to: 'cars#users'

   get 'cars/listing', to: 'cars#listing'

  get 'cars/history', to: 'cars#history'

  get 'cars/rent', to: 'cars#rent'
    post 'cars/rent', to: 'cars#rent'

  post 'cars/:id', to: 'cars#show'

  get 'cars/rented', to: 'cars#rented'
  get 'cars/accept', to: 'cars#accept'

  get 'cars/deactive', to: 'cars#deactive'
   get 'cars/reactivate', to: 'cars#reactivate'

  get 'cars/offhire', to: 'cars#offhire'

  get 'cars/rentpage', to: 'cars#rentpage'
    post 'cars/rentpage', to: 'cars#rentpage'

  get 'homes/aboutus', to: 'homes#aboutus'

   get 'histories/listing', to: 'histories#listing'

  

  get 'histories/new', to: 'histories#new'
  get 'users/show', to: 'users#show'
  
  get 'signup', to: 'users#new'
 

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

  post  'reviews/new/:id', to: 'reviews#new'
  get   'reviews/new/:id', to: 'reviews#new'
  post  'reviews/displays/:id', to: 'reviews#displays'
  get   'reviews/displays/:id', to: 'reviews#displays'

    resources :reviews
    resources :cars
    resources :histories
 resources :users, except: [:new]
end

app/models/car.rb
class Car < ActiveRecord::Base
	require 'carrierwave/orm/activerecord'


	belongs_to :user, :class_name => 'User'
	belongs_to :renter, :class_name => 'User'

	has_many :reviews






	validates :user_id, presence: true
	validates :renter_id, presence: false

	validates :description, :presence => { :message => "Description: cannot be blank ..."}
		mount_uploader :img_url, ImageUploader
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
#before_action :require_login
before_action :set_car, only: [:edit, :update, :show, :destroy, :rent, :offhire, :rentpage, :reactivate, :deactive, :accept]







def index
	@car = Car.paginate(page: params[:page], per_page: 5) #PAGINATION
end
def new
	@car = Car.new 
end
def edit
end

def create
# render plain: params[:car].inspect
@car = Car.new(car_params)
@car.user = User.find(session[:user_id]) #CONTROLS WHO OWNS THE CAR!!
@car.renter_id = 1   #
@car.status = "true"
@car.rentcount = 0
	if @car.save
		flash[:notice] = "Car was successfully created"
		redirect_to car_path(@car)
	else
		render 'new'
	end
end

def update
	if @car.update(car_params)
		if @car.renter_id > 1
			flash[:notice] = "Hired successfully! Check 'My Hire Cars' to see collection details'"
		redirect_to car_path(@car)
		else
		flash[:notice] = "Car Updated successfully"
		redirect_to car_path(@car)
	end
	else
		render 'edit'
	end
end

def show
	#@car.user_id_rent = User.find(session[:user_id]) 
end
def rent
	@user = User.find(session[:user_id])
	@car.renter_id = @user.renter_id
	@user = @car.user
	@user.total = 1
	@user.save
	
    @car.save
end
def accept
	@car.status = "true"
	@user = User.find(session[:user_id])
	@user.total = 0
	@user.save
	@car.save
end

def destroy
	if @car.renter_id == 1
	@car.destroy
	redirect_to cars_path
    else
    flash[:error] = "Car Is On Rent, you can not delete until offhire"
    redirect_to car_path(@car)
end
end

def users
	@car = Car.all 
end
def listing
	@car = Car.all 
end
def reactivate
	@car.status = "true"
	@car.save
end
def deactive
	@car.status = "false"
	@car.save

end
def rentpage

end

def rented
	@car = Car.all
end

def offhire
	@user = User.find(session[:user_id])
	@user.total = 0
	@user.save
	 @car.renter_id = 1	#Stores renter_id back to admin ID
     @car.save
end

def history
	@car = Car.all 
end

private




def set_car
 @car = Car.find(params[:id])
end

def car_params
	params.require(:car).permit(:status, :manufacturer, :model, :fuel, :colour, :engine, :description, :year, :price, :pickup, :postcode, :img_url, :hirestart, :hirefinish, :doors, :transmission, :passengers, :bootspace)
	end
  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_login_url # halts request cycle
    end
  end


end

app/views/cars/deactive.html.erb
   <%= link_to '< Back', cars_path, :class => 'backButtons' %>

Vehicle Deactivated Successfully

app/views/cars/edit.html.erb
<h1> Edit mode </h1>
 <%= render 'form' %>

app/views/cars/index.html.erb
<div id="indexContainer" %>
    <div id="carIndexContainer">
        <div id="headerHire">
            <h2> Cars available </h2>
        </div>
        <% @car.each do |cars| %>
            <% if cars.id == 1 %>
                <% else %>
                    <% if cars.renter_id == 1%>
                        <% if cars.status == "false" %>
                            <% else %>
                                <div class="vehicleIndexHire">
                                    <table id="carIndexTable">
                                        <tr>
                                            <td rowspan="4">
                                                <%= image_tag cars.img_url.url || 'm4.jpg', :size => "270x210" %>
                                            </td>
                                            <td>
                                                <%= image_tag 'Car.png', :size => "50x50" %>
                                            </td>

                                            <td>
                                                <%= image_tag 'House.png', :size => "50x50" %>
                                            </td>
                                            <td>
                                                <%= image_tag 'Fuel.png', :size => "50x50" %>
                                            </td>

                                            <td>
                                                <%= image_tag 'Gears.png', :size => "50x50" %>
                                            </td>

                                        </tr>
                                        <tr>
                                            <td>
                                                <p>
                                                    <%= cars.manufacturer %>
                                                        <%= cars.model %>
                                                </p>
                                            </td>

                                            <td>
                                                <p>
                                                    <%= cars.postcode %>
                                                </p>
                                            </td>

                                            <td>
                                                <p>
                                                    <%= cars.fuel %>
                                                </p>
                                            </td>

                                            <td>
                                                <p>
                                                    <%= cars.transmission %>
                                                </p>
                                            </td>

                                        </tr>
                                        <tr>
                                            <td>
                                                <%= image_tag 'Engine.png', :size => "50x50" %>
                                            </td>

                                            <td>
                                                <%= image_tag 'Year.png', :size => "50x50" %>
                                            </td>

                                            <td>
                                                <%= image_tag 'Price.png', :size => "50x50" %>
                                            </td>

                                            <td>
                                                <%= image_tag 'Review.png', :size => "50x50" %>
                                            </td>

                                        </tr>
                                        <tr>
                                            <td>
                                                <p>
                                                    <%= cars.engine %> Litres </p>
                                            </td>

                                            <td>
                                                <p>
                                                    <%= cars.year %>
                                                </p>
                                            </td>

                                            <td>
                                                <p>24hr Price: £
                                                    <%= cars.price %>
                                                </p>
                                            </td>

                                            <td>
                                                <p>
                                                    <%= link_to 'See Reviews',
                     {controller: 'reviews', action: 'displays', id: cars.id } %>
                                                </p>
                                            </td>

                                        </tr>
                                        <td>
                                            <% if logged_in?%>
                                                <%= link_to 'Book Now', car_path(cars), :class => 'bookButton', :onclick => 'PopUp()'%>
                                                    <% else %>
                                                        <%= link_to 'Book Now', signup_path, :class => 'bookButton' %>
                                                            <% end %>

                                        </td>

                                    </table>

                                </div>
                                <% end %>
                                    <% end %>
                                        <% end %>
                                            <% end %>
                                                <%= will_paginate @car %>
    </div>
</div>

app/views/cars/listing.html.erb
<div id="indexContainer" %>

    <div id="carIndexContainer">
        <%= link_to 'Back', :back, class: "backButtons" %>
            <div id="headerHire">
                <h2> Non-active listings </h2>

            </div>

            <% user = User.find(session[:user_id])%>
                <% @car.each do |cars| %>
                    <% if cars.user_id == user.id %>
                        <% if cars.status == "false" %>

                            <div class="vehicleIndexHire">
                                <table id="carIndexTable">
                                    <tr>
                                        <td rowspan="4">
                                            <%= image_tag cars.img_url.url || 'm4.jpg', :size => "270x210" %>
                                        </td>
                                        <td>
                                            <%= image_tag 'Car.png', :size => "50x50" %>
                                        </td>

                                        <td>
                                            <%= image_tag 'House.png', :size => "50x50" %>
                                        </td>
                                        <td>
                                            <%= image_tag 'Fuel.png', :size => "50x50" %>
                                        </td>

                                        <td>
                                            <%= image_tag 'Colour.png', :size => "50x50" %>
                                        </td>

                                    </tr>
                                    <tr>
                                        <td>
                                            <p>
                                                <%= cars.manufacturer %>
                                                    <%= cars.model %>
                                            </p>
                                        </td>

                                        <td>
                                            <p>
                                                <%= cars.postcode %>
                                            </p>
                                        </td>

                                        <td>
                                            <p>
                                                <%= cars.fuel %>
                                            </p>
                                        </td>

                                        <td>
                                            <p>
                                                <%= cars.colour %>
                                            </p>
                                        </td>

                                    </tr>
                                    <tr>
                                        <td>
                                            <%= image_tag 'Engine.png', :size => "50x50" %>
                                        </td>

                                        <td>
                                            <%= image_tag 'Year.png', :size => "50x50" %>
                                        </td>

                                        <td>
                                            <%= image_tag 'Price.png', :size => "50x50" %>
                                        </td>

                                        <td>
                                            <%= image_tag 'Review.png', :size => "50x50" %>
                                        </td>

                                    </tr>
                                    <tr>
                                        <td>
                                            <p>
                                                <%= cars.engine %>
                                            </p>
                                        </td>

                                        <td>
                                            <p>
                                                <%= cars.year %>
                                            </p>
                                        </td>

                                        <td>
                                            <p>24hr Price: £
                                                <%= cars.price %>
                                            </p>
                                        </td>

                                        <td>
                                            <p>Review: </p>
                                        </td>

                                    </tr>
                                    <td>
                                        <%= link_to "Edit Vehicle", edit_car_path(cars) %> |
                                            <%= link_to 'Relist', controller: 'cars', action: 'reactivate', id: cars.id, :class => 'bookButton' %>
                                                <% @user = User.first %>
                                                    <% if cars.renter_id != @user.id%>
                                                        </br><b> On rent </b>
                                                        <%= link_to 'Off Hire', controller: 'cars', action: 'offhire', id: cars.id, :class => 'bookButton' %>
                                                            <% else %>
                                                                </br><b> Available </b>
                                                                <% end %>
                                                                    <% end %>
                                    </td>
 <% end %>
                                <% end %>
                                </table>

                            </div>
                           

    </div>
</div>

app/views/cars/new.html.erb
<div class="header">
    <h5> Car listing </h5>

    <%= render 'form' %>
</div>

app/views/cars/offhire.html.erb
        <%= link_to 'Back', :back, class: "backButtons" %>
<div id="formContainer">
    <div id="formTable">
<%# OFF HIRE CODING %>
    <% 	var = @car.id %>
        <% @user = User.find_by(renter_id: var) %>
            <% @user.renter_id = 0 %>
                <% 	 @car.renter_id = 1	%>
                    <%     @car.save %>
                        <%     @user.save %>

                            <h1> Off Hire complete </h1>

                            <% time = Time.now %>
                                <% cartime = @car.hirestart %>

                                    <h3> Vehicle hire from: </h3>
                                    <%= @car.hirestart.strftime("%d/%m/%Y | %k:%M") %>
                                        <h3> Until: </h3>
                                        <%= time.strftime("%d/%m/%Y | %k:%M") %>

                                    
    </div>
</div>

app/views/cars/reactivate.html.erb
<%= link_to '< Back', cars_path, :class => 'backButtons' %>

Car Relisted

app/views/cars/show.html.erb
<div id="indexContainer" %>
    <div id="carIndexContainer">

        <div id="headerHire">

            <h1> <%= link_to '<< Back', cars_path, class: "backButtons" %><%= @car.manufacturer %> <%= @car.model %></h1>

        </div>

        <div id="showFlash" %>
            <h2>
    <% flash.each do |name, msg| %>
         <ul>
            <li> <%= msg %></li>
         </ul>
         <%end%>
         <%= yield %>
      </h2>
        </div>
        <div class="vehicleIndexHire1">
            <table id="carIndexTable">
                <tr>
                    <td rowspan="4">
                        <%= image_tag @car.img_url.url || 'm4.jpg', :size => "270x210" %>
                    </td>
                    <td>
                        <%= image_tag 'Car.png', :size => "50x50" %>
                    </td>

                    <td>
                        <%= image_tag 'House.png', :size => "50x50" %>
                    </td>
                    <td>
                        <%= image_tag 'Fuel.png', :size => "50x50" %>
                    </td>

                    <td>
                        <%= image_tag 'Gears.png', :size => "50x50" %>
                    </td>
                    <td>
                        <%= image_tag @car.user.img_url.url || 'unknown.png', :size => "100x70" %>
                    </td>

                </tr>
                <tr>
                    <td>
                        <p>
                            <%= @car.manufacturer %>
                                <%= @car.model %>
                        </p>
                    </td>

                    <td>
                        <p>
                            <%= @car.postcode %>
                        </p>
                    </td>

                    <td>
                        <p>
                            <%= @car.fuel %>
                                <p> (Always full tank) </p>
                    </td>

                    <td>
                        <p>
                            <%= @car.transmission %>
                        </p>
                    </td>
                    <% user = @car.user %>
                        <td>
                            <%= link_to 'Visit Owners Profile', user %>
                        </td>

                </tr>
                <tr>
                    <td>
                        <%= image_tag 'Engine.png', :size => "50x50" %>
                    </td>

                    <td>
                        <%= image_tag 'Year.png', :size => "50x50" %>
                    </td>

                    <td>
                        <%= image_tag 'Price.png', :size => "50x50" %>
                    </td>

                    <td>
                        <%= image_tag 'Passenger.png', :size => "50x50" %>
                    </td>
                    </td>
                    <td rowspan="2">
                        <h4> Owner's notes:</h4>
                        <p>
                            <%= @car.description%>
                        </p>
                    </td>

                </tr>
                <tr>
                    <td>
                        <p>
                            <%= @car.engine %> Litres </p>
                    </td>

                    <td>
                        <p>
                            <%= @car.year %>
                        </p>
                    </td>

                    <td>
                        <p>24hr Price: £
                            <%= @car.price %>
                        </p>
                    </td>

                    <td>
                        <p>
                            <%= @car.passengers %>
                        </p>
                    </td>

                </tr> 
                <td>
                    <% if logged_in? %>
                        <% @user = User.find(session[:user_id]) %>
                            <% if @user.renter_id == 0 %>

                                <% if @car.user_id == @user.id%>

                                    <% else %>
                                        <div class="bookButton">
                                            <%= link_to 'Hire', {controller: 'cars', action: 'rent', id: @car.id} %>
                                        </div>
                                        <% if @car.renter_id == @user.id %>
                                            <div class="bookButton">
                                                <%= link_to 'Add Review',
                                                     controller: 'reviews', action: 'new', id: @car.id  %>
                                            </div>
                                            <% end %>
                                                <% end %>

                                                    <div class="bookButton">
                                                        <%= link_to 'See Reviews',
                                                                {controller: 'reviews', action: 'displays', id: @car.id },{class: "button-to"} %>
                                                    </div>

                                                    <% else %>
                                                        <p> Please unhire your current vehicle to hire this vehicle </p>
                                                        <% end %>

                                                            <% if @car.user_id == session[:user_id] %>
                                                                <%= link_to 'Remove Listing', controller: 'cars', action: 'deactive', id: @car.id, :class => 'bookButton' %>
                                                                    </br>
                                                                    <% if logged_in? %>
                                                                        <%= link_to "Edit Vehicle", edit_car_path(@car) %>
                                                                            <% end %>
                                                                                <% end %>
                                                                                    <% end %>
                </td>

            </table>

        </div>

    </div>
</div>

app/views/cars/users.html.erb
<div id="indexContainer" %>
    <div id="carIndexContainer">
        <%= link_to 'Back', :back, class: "backButtons" %>
            <div id="headerHire">
                <h2> Your listed cars </h2>
            </div>

            <% user = User.find(session[:user_id])%>
                <% @car.each do |cars| %>
                    <% if cars.user.username == user.username || user.username == "Admin" %>
                        <% if cars.status == "false" %>
                            <% else %>
                                <div class="vehicleIndexHire">
                                    <table id="carIndexTable">
                                        <tr>
                                            <td rowspan="4">
                                                <%= image_tag cars.img_url.url || 'm4.jpg', :size => "270x210" %>
                                            </td>
                                            <td>
                                                <%= image_tag 'Car.png', :size => "50x50" %>
                                            </td>

                                            <td>
                                                <%= image_tag 'House.png', :size => "50x50" %>
                                            </td>
                                            <td>
                                                <%= image_tag 'Fuel.png', :size => "50x50" %>
                                            </td>

                                            <td>
                                                <%= image_tag 'Colour.png', :size => "50x50" %>
                                            </td>

                                        </tr>
                                        <tr>
                                            <td>
                                                <p>
                                                    <%= cars.manufacturer %>
                                                        <%= cars.model %>
                                                </p>
                                            </td>

                                            <td>
                                                <p>
                                                    <%= cars.postcode %>
                                                </p>
                                            </td>

                                            <td>
                                                <p>
                                                    <%= cars.fuel %>
                                                </p>
                                            </td>

                                            <td>
                                                <p>
                                                    <%= cars.colour %>
                                                </p>
                                            </td>

                                        </tr>
                                        <tr>
                                            <td>
                                                <%= image_tag 'Engine.png', :size => "50x50" %>
                                            </td>

                                            <td>
                                                <%= image_tag 'Year.png', :size => "50x50" %>
                                            </td>

                                            <td>
                                                <%= image_tag 'Price.png', :size => "50x50" %>
                                            </td>

                                            <td>
                                                <%= image_tag 'Review.png', :size => "50x50" %>
                                            </td>

                                        </tr>
                                        <tr>
                                            <td>
                                                <p>
                                                    <%= cars.engine %>
                                                </p>
                                            </td>

                                            <td>
                                                <p>
                                                    <%= cars.year %>
                                                </p>
                                            </td>

                                            <td>
                                                <p>24hr Price: £
                                                    <%= cars.price %>
                                                </p>
                                            </td>

                                            <td>
                                                <p>Review: </p>
                                            </td>

                                        </tr>
                                        <td>

                            <% @user = User.first %>
                            <% if cars.renter_id != @user.id%>
                            <% if cars.status == "request" %>
                                                                <div class="alarm">You have a request for hire!</div> </br>
                                                                Dates requested</br>
                                                            From
                                                                <%= cars.hirestart.strftime("%d/%m/%Y | %k:%M") %></br>
                                                                until
                                                                <%= cars.hirefinish.strftime("%d/%m/%Y | %k:%M") %></br>
                                                                <% var = cars.renter_id %>
                                                                <% user = User.find_by(renter_id: var) %>
                                                                <%= link_to 'Visit Renters Profile', user %></br>
                                                                <%= link_to 'Deny Request', controller: 'cars', action: 'offhire', id: cars.id, :class => 'bookButton' %>
                                                                <%= link_to 'Accept Request', controller: 'cars', action: 'accept', id: cars.id, :class => 'bookButton' %>
                                        <% else %>
                                                                        </br>Status: <b> On rent </b>
                                                                         <%= link_to 'Off Hire', controller: 'cars', action: 'offhire', id: cars.id, :class => 'bookButton' %>
                                        <% end %>
                                        <% else %>
                                                                                <%= link_to "Edit Vehicle", edit_car_path(cars) %>  |
                                                                                         <%= link_to 'Remove Listing', controller: 'cars', action: 'deactive', id: cars.id, :class => 'bookButton' %>
                                                                                         </br>Status: <b> Available </b>
                                                                
                                    <% end %>

                                        </td>

                                    </table>

                                </div>
                            <% end %>
                    <% end %>
                <% end %>

    </div>
</div>