config/routes.rb
Rails.application.routes.draw do
resources :users
  

  root 'homes#index'

  get 'cars/index', to: 'cars#index'

  get 'cars/new', to: 'cars#new'

  get 'cars/users', to: 'cars#users'

   get 'cars/listing', to: 'cars#listing'

  get 'cars/history', to: 'cars#history'

  get 'cars/rent', to: 'cars#rent'
    post 'cars/rent', to: 'cars#rent'

  post 'cars/:id', to: 'cars#show'

  get 'cars/rented', to: 'cars#rented'
  get 'cars/accept', to: 'cars#accept'

  get 'cars/deactive', to: 'cars#deactive'
   get 'cars/reactivate', to: 'cars#reactivate'

  get 'cars/offhire', to: 'cars#offhire'

  get 'cars/rentpage', to: 'cars#rentpage'
    post 'cars/rentpage', to: 'cars#rentpage'

  get 'homes/aboutus', to: 'homes#aboutus'

   get 'histories/listing', to: 'histories#listing'

  

  get 'histories/new', to: 'histories#new'
  get 'users/show', to: 'users#show'
  
  get 'signup', to: 'users#new'
 

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

  post  'reviews/new/:id', to: 'reviews#new'
  get   'reviews/new/:id', to: 'reviews#new'
  post  'reviews/displays/:id', to: 'reviews#displays'
  get   'reviews/displays/:id', to: 'reviews#displays'

    resources :reviews
    resources :cars
    resources :histories
 resources :users, except: [:new]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Goo Hire</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
            <%= csrf_meta_tags %>


<div class="divv">
<div class="topnav" id="myTopnav">
            
<% if logged_in? %>
<%= link_to "List Now", new_car_path, id: 'nav2' %>
  <div class="dropdown">
    <button class="dropbtn"><%= link_to current_user.username, user_path(current_user), id: 'nav2' %>
    </button>
    <div class="dropdown-content">
        <% @user = User.find(session[:user_id]) %>
        <%= link_to 'Edit My Account', edit_user_path(@user)%>
        <% if @user.total == 1 %>
        <div class="ShowAlert">
      <%= link_to 'My Listed Cars', cars_users_path%>
    </div>
    <% else %>
     <%= link_to 'My Listed Cars', cars_users_path%>
     <% end %>
      <%= link_to 'My Hire cars', cars_rented_path()%>
      <%= link_to 'Rentals History', histories_path %>
      <%= link_to 'Listing History', cars_listing_path %>
       <%= link_to "Log Out", logout_path, method: :delete %>
    </div>
  </div>

  <% else %>
<%= link_to "Sign Up", signup_path, id: 'nav2' %>
<%= link_to "Log In", login_path, id: 'nav2' %>
  <% end %>
  <%= link_to "Rent Now", cars_index_path(), id: 'nav2' %>
   <%= link_to "How GooHire works", homes_aboutus_path, id: 'nav2' %>
   <%= link_to "Home", root_path(), id: 'nav2' %>
   <div class="logo" ><%= image_tag "GooHire.png", :size=> "140x60" %>  </div>
            
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
</div>
</div>
    <div id="bodyContainer">
        <% flash.each do |name, msg| %>
            <ul>
                <li>
                    <%= msg %>
                </li>
            </ul>
            <%end%>
                <%= yield %>
    </div>

</head>

<body>


</body>

</html>

app/views/layouts/messages.html.erb
<div id="flash">
<% flash.each do |name, msg| %>
	<ul>
		<li> <%= msg %></li>
	</ul>
	<%end%>
</div>